#ifndef PRAGMA_MUISCREEN_LIB_H
#define PRAGMA_MUISCREEN_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_MUISCREEN_PROTOS_H
#include <clib/muiscreen_protos.h>
#endif /* CLIB_MUISCREEN_PROTOS_H */

/* "muiscreen.library" */
#pragma amicall(MUIScreenBase, 0x1E, MUIS_AllocPubScreenDesc(a0))
#pragma amicall(MUIScreenBase, 0x24, MUIS_FreePubScreenDesc(a0))
#pragma amicall(MUIScreenBase, 0x2A, MUIS_OpenPubScreen(a0))
#pragma amicall(MUIScreenBase, 0x30, MUIS_ClosePubScreen(a0))
#pragma amicall(MUIScreenBase, 0x36, MUIS_OpenPubFile(a0,d0))
#pragma amicall(MUIScreenBase, 0x3C, MUIS_ClosePubFile(a0))
#pragma amicall(MUIScreenBase, 0x42, MUIS_ReadPubFile(a0))
#pragma amicall(MUIScreenBase, 0x48, MUIS_WritePubFile(a0,a1))
#pragma amicall(MUIScreenBase, 0x4E, MUIS_AddInfoClient(a0))
#pragma amicall(MUIScreenBase, 0x54, MUIS_RemInfoClient(a0))

#endif /* PRAGMA_MUISCREEN_LIB_H */
