#ifndef PRAGMAS_MUIMASTER_PRAGMAS_H
#define PRAGMAS_MUIMASTER_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_MUIMASTER_PROTOS_H
#include <clib/muimaster_protos.h>
#endif /* CLIB_MUIMASTER_PROTOS_H */

/*"muimaster.library" */
/*--- functions in V19 or higher --- */

/* v19 LVO implemented by Zune: matches LibVectors[], muimaster_lib.fd, and */
/* muimaster_pragmas.h (through MUI_EndRefresh at 0xc6).  Trailing mui38dev / */
/* MUI 5 reserved slots (Show, Hide, LayoutObj, Offset, ...) are omitted */
/* until implemented. */

#pragma libcall MUIMasterBase MUI_NewObjectA 1E 9802
#if defined(__SASC_60)
#pragma tagcall MUIMasterBase MUI_NewObject 1E 9802
#endif /* __SASC_60 */
#pragma libcall MUIMasterBase MUI_DisposeObject 24 801
#pragma libcall MUIMasterBase MUI_RequestA 2A BA9821007
#if defined(__SASC_60)
#pragma tagcall MUIMasterBase MUI_Request 2A BA9821007
#endif /* __SASC_60 */
#pragma libcall MUIMasterBase MUI_AllocAslRequest 30 8002
#if defined(__SASC_60)
#pragma tagcall MUIMasterBase MUI_AllocAslRequestTags 30 8002
#endif /* __SASC_60 */
#pragma libcall MUIMasterBase MUI_AslRequest 36 9802
#if defined(__SASC_60)
#pragma tagcall MUIMasterBase MUI_AslRequestTags 36 9802
#endif /* __SASC_60 */
#pragma libcall MUIMasterBase MUI_FreeAslRequest 3C 801
#pragma libcall MUIMasterBase MUI_Error 42 801
#pragma libcall MUIMasterBase MUI_SetError 48 001
#pragma libcall MUIMasterBase MUI_GetClass 4E 801
#pragma libcall MUIMasterBase MUI_FreeClass 54 801
#pragma libcall MUIMasterBase MUI_RequestIDCMP 5A 0802
#pragma libcall MUIMasterBase MUI_RejectIDCMP 60 0802
#pragma libcall MUIMasterBase MUI_Redraw 66 0802
#pragma libcall MUIMasterBase MUI_CreateCustomClass 6C B0A9805
#pragma libcall MUIMasterBase MUI_DeleteCustomClass 72 801
#pragma libcall MUIMasterBase MUI_MakeObjectA 78 8002
#if defined(__SASC_60)
#pragma tagcall MUIMasterBase MUI_MakeObject 78 8002
#endif /* __SASC_60 */
#pragma libcall MUIMasterBase MUI_Layout 7E 43210806
#pragma libcall MUIMasterBase MUI_Priv1 84 801
#pragma libcall MUIMasterBase MUI_Priv2 8A 801
#pragma libcall MUIMasterBase MUI_Priv3 90 801
#pragma libcall MUIMasterBase MUI_Priv4 96 801
#pragma libcall MUIMasterBase MUI_ObtainPen 9C 09803
#pragma libcall MUIMasterBase MUI_ReleasePen A2 0802
#pragma libcall MUIMasterBase MUI_AddClipping A8 3210805
#pragma libcall MUIMasterBase MUI_RemoveClipping AE 9802
#pragma libcall MUIMasterBase MUI_AddClipRegion B4 9802
#pragma libcall MUIMasterBase MUI_RemoveClipRegion BA 9802
#pragma libcall MUIMasterBase MUI_BeginRefresh C0 0802
#pragma libcall MUIMasterBase MUI_EndRefresh C6 0802

#endif /* PRAGMAS_MUIMASTER_PRAGMAS_H */
