#ifndef INLINE_MUISCREEN_PROTOS_H
#define INLINE_MUISCREEN_PROTOS_H

/*
** VBCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/* "muiscreen.library" */
struct MUI_PubScreenDesc *__MUIS_AllocPubScreenDesc(__reg("a6") void *, __reg("a0") struct MUI_PubScreenDesc *src)="\tjsr\t-30(a6)";
#define MUIS_AllocPubScreenDesc(src) __MUIS_AllocPubScreenDesc(MUIScreenBase, (src))

BOOL __MUIS_FreePubScreenDesc(__reg("a6") void *, __reg("a0") struct MUI_PubScreenDesc *psd)="\tjsr\t-36(a6)";
#define MUIS_FreePubScreenDesc(psd) __MUIS_FreePubScreenDesc(MUIScreenBase, (psd))

STRPTR __MUIS_OpenPubScreen(__reg("a6") void *, __reg("a0") struct MUI_PubScreenDesc *desc)="\tjsr\t-42(a6)";
#define MUIS_OpenPubScreen(desc) __MUIS_OpenPubScreen(MUIScreenBase, (desc))

BOOL __MUIS_ClosePubScreen(__reg("a6") void *, __reg("a0") STRPTR name)="\tjsr\t-48(a6)";
#define MUIS_ClosePubScreen(name) __MUIS_ClosePubScreen(MUIScreenBase, (name))

APTR __MUIS_OpenPubFile(__reg("a6") void *, __reg("a0") STRPTR name, __reg("d0") ULONG mode)="\tjsr\t-54(a6)";
#define MUIS_OpenPubFile(name, mode) __MUIS_OpenPubFile(MUIScreenBase, (name), (mode))

void __MUIS_ClosePubFile(__reg("a6") void *, __reg("a0") APTR pf)="\tjsr\t-60(a6)";
#define MUIS_ClosePubFile(pf) __MUIS_ClosePubFile(MUIScreenBase, (pf))

struct MUI_PubScreenDesc *__MUIS_ReadPubFile(__reg("a6") void *, __reg("a0") APTR pf)="\tjsr\t-66(a6)";
#define MUIS_ReadPubFile(pf) __MUIS_ReadPubFile(MUIScreenBase, (pf))

BOOL __MUIS_WritePubFile(__reg("a6") void *, __reg("a0") APTR pf, __reg("a1") struct MUI_PubScreenDesc *desc)="\tjsr\t-72(a6)";
#define MUIS_WritePubFile(pf, desc) __MUIS_WritePubFile(MUIScreenBase, (pf), (desc))

void __MUIS_AddInfoClient(__reg("a6") void *, __reg("a0") struct MUIS_InfoClient *sic)="\tjsr\t-78(a6)";
#define MUIS_AddInfoClient(sic) __MUIS_AddInfoClient(MUIScreenBase, (sic))

void __MUIS_RemInfoClient(__reg("a6") void *, __reg("a0") struct MUIS_InfoClient *sic)="\tjsr\t-84(a6)";
#define MUIS_RemInfoClient(sic) __MUIS_RemInfoClient(MUIScreenBase, (sic))


#endif /* INLINE_MUISCREEN_PROTOS_H */
