#ifndef STRINGS_H
#define STRINGS_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_GENERAL 0
#define MSG_BACKGROUND_COLON 1
#define MSG_BACKGROUND_PRESSED 2
#define MSG_TEXT_BUTTONS 3
#define MSG_FRAME_COLON 4
#define MSG_FONT 5
#define MSG_IMAGE_BUTTONS 6
#define MSG_ADJUST_FRAME 7
#define MSG_CHECKMARKS 8
#define MSG_LOOK_COLON 9
#define MSG_CHECKMARK 10
#define MSG_RADIO_BUTTONS 11
#define MSG_RADIOBUTTON 12
#define MSG_LOOK 13
#define MSG_H 14
#define MSG_V 15
#define MSG_SPACING 16
#define MSG_BELOW 17
#define MSG_ON_ACTIVE 18
#define MSG_CYCLE_GADGET_DESIGN 19
#define MSG_CYCLE 20
#define MSG_POPUP_MENU_CONTROL 21
#define MSG_POSITION 22
#define MSG_LEVEL 23
#define MSG_SPEED 24
#define MSG_POPUP_MENU_DESIGN 25
#define MSG_FRAME 26
#define MSG_ADJUST_BACKGROUND 27
#define MSG_BACKGROUND 28
#define MSG_RECESSED_ENTRIES 29
#define MSG_ABOVE 30
#define MSG_CENTERED 31
#define MSG_STANDARD 32
#define MSG_HILITE 33
#define MSG_3D 34
#define MSG_OUTLINE 35
#define MSG_TITLE 36
#define MSG_COLOR 37
#define MSG_HORIZONTAL 38
#define MSG_VERTICAL 39
#define MSG_REGISTER 40
#define MSG_DEFAULT_SIZE_TRUNCATE_TITLES 41
#define MSG_NORMAL 42
#define MSG_VIRTUAL 43
#define MSG_FRAMED 44
#define MSG_PAGE 45
#define MSG_SHIFTED 46
#define MSG_ALWAYS 47
#define MSG_LINEAR 48
#define MSG_MIXED 49
#define MSG_CONTROL 50
#define MSG_MULTI 51
#define MSG_REFRESH 52
#define MSG_SMOOTH 53
#define MSG_FONTS 54
#define MSG_NORMAL_COLON 55
#define MSG_FIXED 56
#define MSG_LEADING 57
#define MSG_DESIGN 58
#define MSG_INPUT_LISTS 59
#define MSG_READONLY_LISTS 60
#define MSG_CURSOR 61
#define MSG_ACTIVE 62
#define MSG_ACTIVE_SELECTED 63
#define MSG_SELECTED 64
#define MSG_ALWAYS_SOLID 65
#define MSG_GHOSTED_ON_BOX 66
#define MSG_GHOSTED_OUTSIDE_BOX 67
#define MSG_ALWAYS_GHOSTED 68
#define MSG_SHOW_FRAMES 69
#define MSG_SHOW_OBJECTS 70
#define MSG_KL_PRESS 71
#define MSG_KL_TOGGLE 72
#define MSG_KL_UP 73
#define MSG_KL_DOWN 74
#define MSG_KL_PAGE_UP 75
#define MSG_KL_PAGE_DOWN 76
#define MSG_KL_TOP 77
#define MSG_KL_BOTTOM 78
#define MSG_KL_LEFT 79
#define MSG_KL_RIGHT 80
#define MSG_KL_WORD_LEFT 81
#define MSG_KL_WORD_RIGHT 82
#define MSG_KL_LINE_START 83
#define MSG_KL_LINE_END 84
#define MSG_KL_NEXT_GADGET 85
#define MSG_KL_PREV_GADGET 86
#define MSG_KL_GADGET_OFF 87
#define MSG_KL_CLOSE_WINDOW 88
#define MSG_KL_NEXT_WINDOW 89
#define MSG_KL_PREV_WINDOW 90
#define MSG_KL_HELP 91
#define MSG_KL_POPUP 92
#define MSG_DRAG_DROP 93
#define MSG_LEFT_BUTTON 94
#define MSG_MIDDLE_BUTTON 95
#define MSG_AUTOSTART 96
#define MSG_PIXEL 97
#define MSG_BALANCING_GROUPS 98
#define MSG_EXAMPLE 99
#define MSG_TRY_WITH 100
#define MSG_SHIFT 101
#define MSG_TOO 102
#define MSG_KEYBOARD_CONTROL 103
#define MSG_COLOR_ACTIVE_OBJ 104
#define MSG_NEWLOOK 105
#define MSG_CUSTOM 106
#define MSG_ARROWS 107
#define MSG_UP 108
#define MSG_ARROW_UP 109
#define MSG_ARROW_DOWN 110
#define MSG_DOWN 111
#define MSG_LEFT 112
#define MSG_ARROW_LEFT 113
#define MSG_ARROW_RIGHT 114
#define MSG_RIGHT 115
#define MSG_BAR 116
#define MSG_GADGET_TYPE 117
#define MSG_SCROLLER 118
#define MSG_KNOB 119
#define MSG_ARRANGEMENT 120
#define MSG_CONTAINER_DESIGN 121
#define MSG_KNOB_DESIGN 122
#define MSG_EXAMPLE_SLIDERS 123
#define MSG_TEXT_FIELDS 124
#define MSG_EXAMPLE_TEXTFIELD 125
#define MSG_PROGRESS_INDICATOR 126
#define MSG_DEVICE_IMAGES 127
#define MSG_DRAWER 128
#define MSG_HARDDISK 129
#define MSG_DISK 130
#define MSG_RAM 131
#define MSG_VOLUME 132
#define MSG_NETWORK 133
#define MSG_ASSIGN 134
#define MSG_TAPE_IMAGES 135
#define MSG_TAPE_PLAY 136
#define MSG_TAPE_PLAYBACK 137
#define MSG_TAPE_PAUSE 138
#define MSG_TAPE_STOP 139
#define MSG_TAPE_RECORD 140
#define MSG_TAPE_UP 141
#define MSG_TAPE_DOWN 142
#define MSG_STRING_FRAME 143
#define MSG_SPECIAL_POPUP_BUTTONS 144
#define MSG_POPUP 145
#define MSG_DEFAULT 146
#define MSG_FILE 147
#define MSG_POPUP_FILE 148
#define MSG_POPUP_DRAWER 149
#define MSG_INACTIVE_STRING_COLORS 150
#define MSG_TEXT 151
#define MSG_ACTIVE_STRING_COLORS 152
#define MSG_MARKED_STRING_COLORS 153
#define MSG_EXAMPLE_STRING_GADGET 154
#define MSG_FORGET_ON_EXIT 155
#define MSG_REMEMBER_ON_EXIT 156
#define MSG_SAVE_ON_EXIT 157
#define MSG_SMART 158
#define MSG_SIMPLE 159
#define MSG_WITHOUT_CLEAR 160
#define MSG_WITH_CLEAR 161
#define MSG_POSITIONS 162
#define MSG_REDRAW 163
#define MSG_TINY 164
#define MSG_BIG 165
#define MSG_WINDOW 166
#define MSG_REQUESTER 167
#define MSG_L 168
#define MSG_T 169
#define MSG_R 170
#define MSG_B 171
#define MSG_BUTTONS 172
#define MSG_WINTITLE1 173
#define MSG_WINTITLE2 174
#define MSG_MEN_PROJECT 175
#define MSG_MEN_OPEN 176
#define MSG_MEN_OPEN_SC 177
#define MSG_MEN_APPEND 178
#define MSG_MEN_SAVEAS 179
#define MSG_MEN_SAVEAS_SC 180
#define MSG_MEN_ABOUT 181
#define MSG_MEN_ABOUT_SC 182
#define MSG_MEN_QUIT 183
#define MSG_MEN_QUIT_SC 184
#define MSG_FRAME_CLIPBOARD 185
#define MSG_IMAGE_CLIPBOARD 186
#define MSG_GAD_TEST 187
#define MSG_GAD_SAVE 188
#define MSG_GAD_USE 189
#define MSG_GAD_CANCEL 190
#define MSG_DSC_SYSTEM 191
#define MSG_DSC_WINDOWS 192
#define MSG_DSC_GROUPS 193
#define MSG_DSC_BUTTONS 194
#define MSG_DSC_CYCLES 195
#define MSG_DSC_SLIDERS 196
#define MSG_DSC_SCROLLBARS 197
#define MSG_DSC_LISTVIEWS 198
#define MSG_DSC_STRINGS 199
#define MSG_DSC_NAVIGATION 200
#define MSG_DSC_SPECIAL 201
#define MSG_DSC_FRAMES 202
#define MSG_ADJUST_PEN 203
#define MSG_CUSTOMFRAMES 204
#define MSG_PUBLIC_SCREEN 205
#define MSG_NAME 206
#define MSG_CALL_INSPECTOR 207
#define MSG_POP_TO_FRONT 208
#define MSG_ICONIFICATION 209
#define MSG_HOTKEY 210
#define MSG_SHOW 211
#define MSG_ICON 212
#define MSG_MENU 213
#define MSG_ON_STARTUP 214
#define MSG_INTERFACES 215
#define MSG_AREXX 216
#define MSG_BUBBLE_HELP 217
#define MSG_FIRST_BUBBLE 218
#define MSG_NEXT_BUBBLE 219

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_GENERAL_STR "General"
#define MSG_BACKGROUND_COLON_STR "Background:"
#define MSG_BACKGROUND_PRESSED_STR "Background in\npressed state:"
#define MSG_TEXT_BUTTONS_STR "Text Buttons"
#define MSG_FRAME_COLON_STR "Frame:"
#define MSG_FONT_STR "Font:"
#define MSG_IMAGE_BUTTONS_STR "Image Buttons"
#define MSG_ADJUST_FRAME_STR "Adjust Frame"
#define MSG_CHECKMARKS_STR "Checkmarks"
#define MSG_LOOK_COLON_STR "Look:"
#define MSG_CHECKMARK_STR "Checkmark"
#define MSG_RADIO_BUTTONS_STR "Radio Buttons"
#define MSG_RADIOBUTTON_STR "Radiobutton"
#define MSG_LOOK_STR "Look"
#define MSG_H_STR "H"
#define MSG_V_STR "V"
#define MSG_SPACING_STR "Spacing"
#define MSG_BELOW_STR "below"
#define MSG_ON_ACTIVE_STR "on active"
#define MSG_CYCLE_GADGET_DESIGN_STR "Cycle Gadget Design"
#define MSG_CYCLE_STR "Cycle"
#define MSG_POPUP_MENU_CONTROL_STR "Popup Menu Control"
#define MSG_POSITION_STR "Position:"
#define MSG_LEVEL_STR "Level:"
#define MSG_SPEED_STR "Speed:"
#define MSG_POPUP_MENU_DESIGN_STR "Popup Menu Design"
#define MSG_FRAME_STR "Frame"
#define MSG_ADJUST_BACKGROUND_STR "Adjust Background"
#define MSG_BACKGROUND_STR "Background"
#define MSG_RECESSED_ENTRIES_STR "Recessed Entries:"
#define MSG_ABOVE_STR "above"
#define MSG_CENTERED_STR "centered"
#define MSG_STANDARD_STR "standard"
#define MSG_HILITE_STR "hilite"
#define MSG_3D_STR "3d"
#define MSG_OUTLINE_STR "outline"
#define MSG_TITLE_STR "Title"
#define MSG_COLOR_STR "Color:"
#define MSG_HORIZONTAL_STR "Horizontal:"
#define MSG_VERTICAL_STR "Vertical:"
#define MSG_REGISTER_STR "Register"
#define MSG_DEFAULT_SIZE_TRUNCATE_TITLES_STR "Default size truncate titles:"
#define MSG_NORMAL_STR "Normal"
#define MSG_VIRTUAL_STR "Virtual"
#define MSG_FRAMED_STR "Framed"
#define MSG_PAGE_STR "Page"
#define MSG_SHIFTED_STR "shifted"
#define MSG_ALWAYS_STR "always"
#define MSG_LINEAR_STR "linear"
#define MSG_MIXED_STR "mixed"
#define MSG_CONTROL_STR "Control"
#define MSG_MULTI_STR "Multi:"
#define MSG_REFRESH_STR "Refresh:"
#define MSG_SMOOTH_STR "Smooth:"
#define MSG_FONTS_STR "Fonts"
#define MSG_NORMAL_COLON_STR "Normal:"
#define MSG_FIXED_STR "Fixed:"
#define MSG_LEADING_STR "Leading"
#define MSG_DESIGN_STR "Design"
#define MSG_INPUT_LISTS_STR "Input \nLists:"
#define MSG_READONLY_LISTS_STR "Readonly \nLists:"
#define MSG_CURSOR_STR "Cursor"
#define MSG_ACTIVE_STR "Active:"
#define MSG_ACTIVE_SELECTED_STR "Active &\nSelected:"
#define MSG_SELECTED_STR "Selected:"
#define MSG_ALWAYS_SOLID_STR "always solid"
#define MSG_GHOSTED_ON_BOX_STR "ghosted on box"
#define MSG_GHOSTED_OUTSIDE_BOX_STR "ghosted outside box"
#define MSG_ALWAYS_GHOSTED_STR "always ghosted"
#define MSG_SHOW_FRAMES_STR "show frames"
#define MSG_SHOW_OBJECTS_STR "show objects"
#define MSG_KL_PRESS_STR "Press:"
#define MSG_KL_TOGGLE_STR "Toggle:"
#define MSG_KL_UP_STR "Up:"
#define MSG_KL_DOWN_STR "Down:"
#define MSG_KL_PAGE_UP_STR "Page up:"
#define MSG_KL_PAGE_DOWN_STR "Page down:"
#define MSG_KL_TOP_STR "Top:"
#define MSG_KL_BOTTOM_STR "Bottom:"
#define MSG_KL_LEFT_STR "Left:"
#define MSG_KL_RIGHT_STR "Right:"
#define MSG_KL_WORD_LEFT_STR "Word left:"
#define MSG_KL_WORD_RIGHT_STR "Word right:"
#define MSG_KL_LINE_START_STR "Line start:"
#define MSG_KL_LINE_END_STR "Line end:"
#define MSG_KL_NEXT_GADGET_STR "Next gadget:"
#define MSG_KL_PREV_GADGET_STR "Prev. gadget:"
#define MSG_KL_GADGET_OFF_STR "Gadget off:"
#define MSG_KL_CLOSE_WINDOW_STR "Close window:"
#define MSG_KL_NEXT_WINDOW_STR "Next window:"
#define MSG_KL_PREV_WINDOW_STR "Prev. window:"
#define MSG_KL_HELP_STR "Help:"
#define MSG_KL_POPUP_STR "Popup:"
#define MSG_DRAG_DROP_STR "Drag & Drop"
#define MSG_LEFT_BUTTON_STR "Left Button:"
#define MSG_MIDDLE_BUTTON_STR "Middle Button:"
#define MSG_AUTOSTART_STR "Autostart:"
#define MSG_PIXEL_STR "%ld pixel"
#define MSG_BALANCING_GROUPS_STR "Balancing Groups"
#define MSG_EXAMPLE_STR "Example:"
#define MSG_TRY_WITH_STR "Try with"
#define MSG_SHIFT_STR "shift"
#define MSG_TOO_STR "too!"
#define MSG_KEYBOARD_CONTROL_STR "Keyboard Control"
#define MSG_COLOR_ACTIVE_OBJ_STR "Color of active object:"
#define MSG_NEWLOOK_STR "newlook"
#define MSG_CUSTOM_STR "custom"
#define MSG_ARROWS_STR "Arrows"
#define MSG_UP_STR "up"
#define MSG_ARROW_UP_STR "Arrow up"
#define MSG_ARROW_DOWN_STR "Arrow down"
#define MSG_DOWN_STR "down"
#define MSG_LEFT_STR "left"
#define MSG_ARROW_LEFT_STR "Arrow left"
#define MSG_ARROW_RIGHT_STR "Arrow right"
#define MSG_RIGHT_STR "right"
#define MSG_BAR_STR "Bar"
#define MSG_GADGET_TYPE_STR "Gadget Type:"
#define MSG_SCROLLER_STR "Scroller"
#define MSG_KNOB_STR "Knob"
#define MSG_ARRANGEMENT_STR "Arrangement"
#define MSG_CONTAINER_DESIGN_STR "Container Design"
#define MSG_KNOB_DESIGN_STR "Knob Design"
#define MSG_EXAMPLE_SLIDERS_STR "Example Sliders"
#define MSG_TEXT_FIELDS_STR "Text fields"
#define MSG_EXAMPLE_TEXTFIELD_STR "Example Textfield"
#define MSG_PROGRESS_INDICATOR_STR "Progress Indicator"
#define MSG_DEVICE_IMAGES_STR "Device Images"
#define MSG_DRAWER_STR "Drawer"
#define MSG_HARDDISK_STR "Harddisk"
#define MSG_DISK_STR "Disk"
#define MSG_RAM_STR "RAM"
#define MSG_VOLUME_STR "Volume"
#define MSG_NETWORK_STR "Network"
#define MSG_ASSIGN_STR "Assign"
#define MSG_TAPE_IMAGES_STR "Tape Images"
#define MSG_TAPE_PLAY_STR "Tape play"
#define MSG_TAPE_PLAYBACK_STR "Tape playback"
#define MSG_TAPE_PAUSE_STR "Tape pause"
#define MSG_TAPE_STOP_STR "Tape stop"
#define MSG_TAPE_RECORD_STR "Tape record"
#define MSG_TAPE_UP_STR "Tape up"
#define MSG_TAPE_DOWN_STR "Tape down"
#define MSG_STRING_FRAME_STR "String Frame"
#define MSG_SPECIAL_POPUP_BUTTONS_STR "Special Popup Buttons"
#define MSG_POPUP_STR "Popup"
#define MSG_DEFAULT_STR "Default"
#define MSG_FILE_STR "File"
#define MSG_POPUP_FILE_STR "Popup file"
#define MSG_POPUP_DRAWER_STR "Popup drawer"
#define MSG_INACTIVE_STRING_COLORS_STR "Inactive String Colors"
#define MSG_TEXT_STR "Text"
#define MSG_ACTIVE_STRING_COLORS_STR "Active String Colors"
#define MSG_MARKED_STRING_COLORS_STR "Marked String Colors"
#define MSG_EXAMPLE_STRING_GADGET_STR "Example String Gadget"
#define MSG_FORGET_ON_EXIT_STR "forget on exit"
#define MSG_REMEMBER_ON_EXIT_STR "remember on exit"
#define MSG_SAVE_ON_EXIT_STR "save on exit"
#define MSG_SMART_STR "smart"
#define MSG_SIMPLE_STR "simple"
#define MSG_WITHOUT_CLEAR_STR "without clear"
#define MSG_WITH_CLEAR_STR "with clear"
#define MSG_POSITIONS_STR "Positions:"
#define MSG_REDRAW_STR "Redraw:"
#define MSG_TINY_STR "Tiny:"
#define MSG_BIG_STR "Big:"
#define MSG_WINDOW_STR "Window"
#define MSG_REQUESTER_STR "Requester"
#define MSG_L_STR "L"
#define MSG_T_STR "T"
#define MSG_R_STR "R"
#define MSG_B_STR "B"
#define MSG_BUTTONS_STR "Buttons"
#define MSG_WINTITLE1_STR "mushin - Global Prefs"
#define MSG_WINTITLE2_STR "mushin - Prefs for : %s"
#define MSG_MEN_PROJECT_STR "Project"
#define MSG_MEN_OPEN_STR "Open ..."
#define MSG_MEN_OPEN_SC_STR "O"
#define MSG_MEN_APPEND_STR "Append ..."
#define MSG_MEN_SAVEAS_STR "Save As ..."
#define MSG_MEN_SAVEAS_SC_STR "A"
#define MSG_MEN_ABOUT_STR "About mushin ..."
#define MSG_MEN_ABOUT_SC_STR "?"
#define MSG_MEN_QUIT_STR "Quit"
#define MSG_MEN_QUIT_SC_STR "Q"
#define MSG_FRAME_CLIPBOARD_STR "Frame Clipboard"
#define MSG_IMAGE_CLIPBOARD_STR "Image Clipboard"
#define MSG_GAD_TEST_STR "_Test"
#define MSG_GAD_SAVE_STR "_Save"
#define MSG_GAD_USE_STR "_Use"
#define MSG_GAD_CANCEL_STR "_Cancel"
#define MSG_DSC_SYSTEM_STR "System"
#define MSG_DSC_WINDOWS_STR "Windows"
#define MSG_DSC_GROUPS_STR "Groups"
#define MSG_DSC_BUTTONS_STR "Buttons"
#define MSG_DSC_CYCLES_STR "Cycles"
#define MSG_DSC_SLIDERS_STR "Sliders"
#define MSG_DSC_SCROLLBARS_STR "Scrollbars"
#define MSG_DSC_LISTVIEWS_STR "Listviews"
#define MSG_DSC_STRINGS_STR "Strings"
#define MSG_DSC_NAVIGATION_STR "Navigation"
#define MSG_DSC_SPECIAL_STR "Special"
#define MSG_DSC_FRAMES_STR "Frames"
#define MSG_ADJUST_PEN_STR "Adjust Pen"
#define MSG_CUSTOMFRAMES_STR "Customframes"
#define MSG_PUBLIC_SCREEN_STR "Public Screen"
#define MSG_NAME_STR "Name:"
#define MSG_CALL_INSPECTOR_STR "Inspector..."
#define MSG_POP_TO_FRONT_STR "Pop to front"
#define MSG_ICONIFICATION_STR "Iconification"
#define MSG_HOTKEY_STR "Hotkey:"
#define MSG_SHOW_STR "Show:"
#define MSG_ICON_STR "Icon"
#define MSG_MENU_STR "Menu"
#define MSG_ON_STARTUP_STR "On startup"
#define MSG_INTERFACES_STR "Interfaces"
#define MSG_AREXX_STR "ARexx"
#define MSG_BUBBLE_HELP_STR "Bubble Help"
#define MSG_FIRST_BUBBLE_STR "First bubble:"
#define MSG_NEXT_BUBBLE_STR "Next bubble:"

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
    LONG   cca_ID;
    STRPTR cca_Str;
};

static const struct CatCompArrayType CatCompArray[] =
{
    {MSG_GENERAL,(STRPTR)MSG_GENERAL_STR},
    {MSG_BACKGROUND_COLON,(STRPTR)MSG_BACKGROUND_COLON_STR},
    {MSG_BACKGROUND_PRESSED,(STRPTR)MSG_BACKGROUND_PRESSED_STR},
    {MSG_TEXT_BUTTONS,(STRPTR)MSG_TEXT_BUTTONS_STR},
    {MSG_FRAME_COLON,(STRPTR)MSG_FRAME_COLON_STR},
    {MSG_FONT,(STRPTR)MSG_FONT_STR},
    {MSG_IMAGE_BUTTONS,(STRPTR)MSG_IMAGE_BUTTONS_STR},
    {MSG_ADJUST_FRAME,(STRPTR)MSG_ADJUST_FRAME_STR},
    {MSG_CHECKMARKS,(STRPTR)MSG_CHECKMARKS_STR},
    {MSG_LOOK_COLON,(STRPTR)MSG_LOOK_COLON_STR},
    {MSG_CHECKMARK,(STRPTR)MSG_CHECKMARK_STR},
    {MSG_RADIO_BUTTONS,(STRPTR)MSG_RADIO_BUTTONS_STR},
    {MSG_RADIOBUTTON,(STRPTR)MSG_RADIOBUTTON_STR},
    {MSG_LOOK,(STRPTR)MSG_LOOK_STR},
    {MSG_H,(STRPTR)MSG_H_STR},
    {MSG_V,(STRPTR)MSG_V_STR},
    {MSG_SPACING,(STRPTR)MSG_SPACING_STR},
    {MSG_BELOW,(STRPTR)MSG_BELOW_STR},
    {MSG_ON_ACTIVE,(STRPTR)MSG_ON_ACTIVE_STR},
    {MSG_CYCLE_GADGET_DESIGN,(STRPTR)MSG_CYCLE_GADGET_DESIGN_STR},
    {MSG_CYCLE,(STRPTR)MSG_CYCLE_STR},
    {MSG_POPUP_MENU_CONTROL,(STRPTR)MSG_POPUP_MENU_CONTROL_STR},
    {MSG_POSITION,(STRPTR)MSG_POSITION_STR},
    {MSG_LEVEL,(STRPTR)MSG_LEVEL_STR},
    {MSG_SPEED,(STRPTR)MSG_SPEED_STR},
    {MSG_POPUP_MENU_DESIGN,(STRPTR)MSG_POPUP_MENU_DESIGN_STR},
    {MSG_FRAME,(STRPTR)MSG_FRAME_STR},
    {MSG_ADJUST_BACKGROUND,(STRPTR)MSG_ADJUST_BACKGROUND_STR},
    {MSG_BACKGROUND,(STRPTR)MSG_BACKGROUND_STR},
    {MSG_RECESSED_ENTRIES,(STRPTR)MSG_RECESSED_ENTRIES_STR},
    {MSG_ABOVE,(STRPTR)MSG_ABOVE_STR},
    {MSG_CENTERED,(STRPTR)MSG_CENTERED_STR},
    {MSG_STANDARD,(STRPTR)MSG_STANDARD_STR},
    {MSG_HILITE,(STRPTR)MSG_HILITE_STR},
    {MSG_3D,(STRPTR)MSG_3D_STR},
    {MSG_OUTLINE,(STRPTR)MSG_OUTLINE_STR},
    {MSG_TITLE,(STRPTR)MSG_TITLE_STR},
    {MSG_COLOR,(STRPTR)MSG_COLOR_STR},
    {MSG_HORIZONTAL,(STRPTR)MSG_HORIZONTAL_STR},
    {MSG_VERTICAL,(STRPTR)MSG_VERTICAL_STR},
    {MSG_REGISTER,(STRPTR)MSG_REGISTER_STR},
    {MSG_DEFAULT_SIZE_TRUNCATE_TITLES,(STRPTR)MSG_DEFAULT_SIZE_TRUNCATE_TITLES_STR},
    {MSG_NORMAL,(STRPTR)MSG_NORMAL_STR},
    {MSG_VIRTUAL,(STRPTR)MSG_VIRTUAL_STR},
    {MSG_FRAMED,(STRPTR)MSG_FRAMED_STR},
    {MSG_PAGE,(STRPTR)MSG_PAGE_STR},
    {MSG_SHIFTED,(STRPTR)MSG_SHIFTED_STR},
    {MSG_ALWAYS,(STRPTR)MSG_ALWAYS_STR},
    {MSG_LINEAR,(STRPTR)MSG_LINEAR_STR},
    {MSG_MIXED,(STRPTR)MSG_MIXED_STR},
    {MSG_CONTROL,(STRPTR)MSG_CONTROL_STR},
    {MSG_MULTI,(STRPTR)MSG_MULTI_STR},
    {MSG_REFRESH,(STRPTR)MSG_REFRESH_STR},
    {MSG_SMOOTH,(STRPTR)MSG_SMOOTH_STR},
    {MSG_FONTS,(STRPTR)MSG_FONTS_STR},
    {MSG_NORMAL_COLON,(STRPTR)MSG_NORMAL_COLON_STR},
    {MSG_FIXED,(STRPTR)MSG_FIXED_STR},
    {MSG_LEADING,(STRPTR)MSG_LEADING_STR},
    {MSG_DESIGN,(STRPTR)MSG_DESIGN_STR},
    {MSG_INPUT_LISTS,(STRPTR)MSG_INPUT_LISTS_STR},
    {MSG_READONLY_LISTS,(STRPTR)MSG_READONLY_LISTS_STR},
    {MSG_CURSOR,(STRPTR)MSG_CURSOR_STR},
    {MSG_ACTIVE,(STRPTR)MSG_ACTIVE_STR},
    {MSG_ACTIVE_SELECTED,(STRPTR)MSG_ACTIVE_SELECTED_STR},
    {MSG_SELECTED,(STRPTR)MSG_SELECTED_STR},
    {MSG_ALWAYS_SOLID,(STRPTR)MSG_ALWAYS_SOLID_STR},
    {MSG_GHOSTED_ON_BOX,(STRPTR)MSG_GHOSTED_ON_BOX_STR},
    {MSG_GHOSTED_OUTSIDE_BOX,(STRPTR)MSG_GHOSTED_OUTSIDE_BOX_STR},
    {MSG_ALWAYS_GHOSTED,(STRPTR)MSG_ALWAYS_GHOSTED_STR},
    {MSG_SHOW_FRAMES,(STRPTR)MSG_SHOW_FRAMES_STR},
    {MSG_SHOW_OBJECTS,(STRPTR)MSG_SHOW_OBJECTS_STR},
    {MSG_KL_PRESS,(STRPTR)MSG_KL_PRESS_STR},
    {MSG_KL_TOGGLE,(STRPTR)MSG_KL_TOGGLE_STR},
    {MSG_KL_UP,(STRPTR)MSG_KL_UP_STR},
    {MSG_KL_DOWN,(STRPTR)MSG_KL_DOWN_STR},
    {MSG_KL_PAGE_UP,(STRPTR)MSG_KL_PAGE_UP_STR},
    {MSG_KL_PAGE_DOWN,(STRPTR)MSG_KL_PAGE_DOWN_STR},
    {MSG_KL_TOP,(STRPTR)MSG_KL_TOP_STR},
    {MSG_KL_BOTTOM,(STRPTR)MSG_KL_BOTTOM_STR},
    {MSG_KL_LEFT,(STRPTR)MSG_KL_LEFT_STR},
    {MSG_KL_RIGHT,(STRPTR)MSG_KL_RIGHT_STR},
    {MSG_KL_WORD_LEFT,(STRPTR)MSG_KL_WORD_LEFT_STR},
    {MSG_KL_WORD_RIGHT,(STRPTR)MSG_KL_WORD_RIGHT_STR},
    {MSG_KL_LINE_START,(STRPTR)MSG_KL_LINE_START_STR},
    {MSG_KL_LINE_END,(STRPTR)MSG_KL_LINE_END_STR},
    {MSG_KL_NEXT_GADGET,(STRPTR)MSG_KL_NEXT_GADGET_STR},
    {MSG_KL_PREV_GADGET,(STRPTR)MSG_KL_PREV_GADGET_STR},
    {MSG_KL_GADGET_OFF,(STRPTR)MSG_KL_GADGET_OFF_STR},
    {MSG_KL_CLOSE_WINDOW,(STRPTR)MSG_KL_CLOSE_WINDOW_STR},
    {MSG_KL_NEXT_WINDOW,(STRPTR)MSG_KL_NEXT_WINDOW_STR},
    {MSG_KL_PREV_WINDOW,(STRPTR)MSG_KL_PREV_WINDOW_STR},
    {MSG_KL_HELP,(STRPTR)MSG_KL_HELP_STR},
    {MSG_KL_POPUP,(STRPTR)MSG_KL_POPUP_STR},
    {MSG_DRAG_DROP,(STRPTR)MSG_DRAG_DROP_STR},
    {MSG_LEFT_BUTTON,(STRPTR)MSG_LEFT_BUTTON_STR},
    {MSG_MIDDLE_BUTTON,(STRPTR)MSG_MIDDLE_BUTTON_STR},
    {MSG_AUTOSTART,(STRPTR)MSG_AUTOSTART_STR},
    {MSG_PIXEL,(STRPTR)MSG_PIXEL_STR},
    {MSG_BALANCING_GROUPS,(STRPTR)MSG_BALANCING_GROUPS_STR},
    {MSG_EXAMPLE,(STRPTR)MSG_EXAMPLE_STR},
    {MSG_TRY_WITH,(STRPTR)MSG_TRY_WITH_STR},
    {MSG_SHIFT,(STRPTR)MSG_SHIFT_STR},
    {MSG_TOO,(STRPTR)MSG_TOO_STR},
    {MSG_KEYBOARD_CONTROL,(STRPTR)MSG_KEYBOARD_CONTROL_STR},
    {MSG_COLOR_ACTIVE_OBJ,(STRPTR)MSG_COLOR_ACTIVE_OBJ_STR},
    {MSG_NEWLOOK,(STRPTR)MSG_NEWLOOK_STR},
    {MSG_CUSTOM,(STRPTR)MSG_CUSTOM_STR},
    {MSG_ARROWS,(STRPTR)MSG_ARROWS_STR},
    {MSG_UP,(STRPTR)MSG_UP_STR},
    {MSG_ARROW_UP,(STRPTR)MSG_ARROW_UP_STR},
    {MSG_ARROW_DOWN,(STRPTR)MSG_ARROW_DOWN_STR},
    {MSG_DOWN,(STRPTR)MSG_DOWN_STR},
    {MSG_LEFT,(STRPTR)MSG_LEFT_STR},
    {MSG_ARROW_LEFT,(STRPTR)MSG_ARROW_LEFT_STR},
    {MSG_ARROW_RIGHT,(STRPTR)MSG_ARROW_RIGHT_STR},
    {MSG_RIGHT,(STRPTR)MSG_RIGHT_STR},
    {MSG_BAR,(STRPTR)MSG_BAR_STR},
    {MSG_GADGET_TYPE,(STRPTR)MSG_GADGET_TYPE_STR},
    {MSG_SCROLLER,(STRPTR)MSG_SCROLLER_STR},
    {MSG_KNOB,(STRPTR)MSG_KNOB_STR},
    {MSG_ARRANGEMENT,(STRPTR)MSG_ARRANGEMENT_STR},
    {MSG_CONTAINER_DESIGN,(STRPTR)MSG_CONTAINER_DESIGN_STR},
    {MSG_KNOB_DESIGN,(STRPTR)MSG_KNOB_DESIGN_STR},
    {MSG_EXAMPLE_SLIDERS,(STRPTR)MSG_EXAMPLE_SLIDERS_STR},
    {MSG_TEXT_FIELDS,(STRPTR)MSG_TEXT_FIELDS_STR},
    {MSG_EXAMPLE_TEXTFIELD,(STRPTR)MSG_EXAMPLE_TEXTFIELD_STR},
    {MSG_PROGRESS_INDICATOR,(STRPTR)MSG_PROGRESS_INDICATOR_STR},
    {MSG_DEVICE_IMAGES,(STRPTR)MSG_DEVICE_IMAGES_STR},
    {MSG_DRAWER,(STRPTR)MSG_DRAWER_STR},
    {MSG_HARDDISK,(STRPTR)MSG_HARDDISK_STR},
    {MSG_DISK,(STRPTR)MSG_DISK_STR},
    {MSG_RAM,(STRPTR)MSG_RAM_STR},
    {MSG_VOLUME,(STRPTR)MSG_VOLUME_STR},
    {MSG_NETWORK,(STRPTR)MSG_NETWORK_STR},
    {MSG_ASSIGN,(STRPTR)MSG_ASSIGN_STR},
    {MSG_TAPE_IMAGES,(STRPTR)MSG_TAPE_IMAGES_STR},
    {MSG_TAPE_PLAY,(STRPTR)MSG_TAPE_PLAY_STR},
    {MSG_TAPE_PLAYBACK,(STRPTR)MSG_TAPE_PLAYBACK_STR},
    {MSG_TAPE_PAUSE,(STRPTR)MSG_TAPE_PAUSE_STR},
    {MSG_TAPE_STOP,(STRPTR)MSG_TAPE_STOP_STR},
    {MSG_TAPE_RECORD,(STRPTR)MSG_TAPE_RECORD_STR},
    {MSG_TAPE_UP,(STRPTR)MSG_TAPE_UP_STR},
    {MSG_TAPE_DOWN,(STRPTR)MSG_TAPE_DOWN_STR},
    {MSG_STRING_FRAME,(STRPTR)MSG_STRING_FRAME_STR},
    {MSG_SPECIAL_POPUP_BUTTONS,(STRPTR)MSG_SPECIAL_POPUP_BUTTONS_STR},
    {MSG_POPUP,(STRPTR)MSG_POPUP_STR},
    {MSG_DEFAULT,(STRPTR)MSG_DEFAULT_STR},
    {MSG_FILE,(STRPTR)MSG_FILE_STR},
    {MSG_POPUP_FILE,(STRPTR)MSG_POPUP_FILE_STR},
    {MSG_POPUP_DRAWER,(STRPTR)MSG_POPUP_DRAWER_STR},
    {MSG_INACTIVE_STRING_COLORS,(STRPTR)MSG_INACTIVE_STRING_COLORS_STR},
    {MSG_TEXT,(STRPTR)MSG_TEXT_STR},
    {MSG_ACTIVE_STRING_COLORS,(STRPTR)MSG_ACTIVE_STRING_COLORS_STR},
    {MSG_MARKED_STRING_COLORS,(STRPTR)MSG_MARKED_STRING_COLORS_STR},
    {MSG_EXAMPLE_STRING_GADGET,(STRPTR)MSG_EXAMPLE_STRING_GADGET_STR},
    {MSG_FORGET_ON_EXIT,(STRPTR)MSG_FORGET_ON_EXIT_STR},
    {MSG_REMEMBER_ON_EXIT,(STRPTR)MSG_REMEMBER_ON_EXIT_STR},
    {MSG_SAVE_ON_EXIT,(STRPTR)MSG_SAVE_ON_EXIT_STR},
    {MSG_SMART,(STRPTR)MSG_SMART_STR},
    {MSG_SIMPLE,(STRPTR)MSG_SIMPLE_STR},
    {MSG_WITHOUT_CLEAR,(STRPTR)MSG_WITHOUT_CLEAR_STR},
    {MSG_WITH_CLEAR,(STRPTR)MSG_WITH_CLEAR_STR},
    {MSG_POSITIONS,(STRPTR)MSG_POSITIONS_STR},
    {MSG_REDRAW,(STRPTR)MSG_REDRAW_STR},
    {MSG_TINY,(STRPTR)MSG_TINY_STR},
    {MSG_BIG,(STRPTR)MSG_BIG_STR},
    {MSG_WINDOW,(STRPTR)MSG_WINDOW_STR},
    {MSG_REQUESTER,(STRPTR)MSG_REQUESTER_STR},
    {MSG_L,(STRPTR)MSG_L_STR},
    {MSG_T,(STRPTR)MSG_T_STR},
    {MSG_R,(STRPTR)MSG_R_STR},
    {MSG_B,(STRPTR)MSG_B_STR},
    {MSG_BUTTONS,(STRPTR)MSG_BUTTONS_STR},
    {MSG_WINTITLE1,(STRPTR)MSG_WINTITLE1_STR},
    {MSG_WINTITLE2,(STRPTR)MSG_WINTITLE2_STR},
    {MSG_MEN_PROJECT,(STRPTR)MSG_MEN_PROJECT_STR},
    {MSG_MEN_OPEN,(STRPTR)MSG_MEN_OPEN_STR},
    {MSG_MEN_OPEN_SC,(STRPTR)MSG_MEN_OPEN_SC_STR},
    {MSG_MEN_APPEND,(STRPTR)MSG_MEN_APPEND_STR},
    {MSG_MEN_SAVEAS,(STRPTR)MSG_MEN_SAVEAS_STR},
    {MSG_MEN_SAVEAS_SC,(STRPTR)MSG_MEN_SAVEAS_SC_STR},
    {MSG_MEN_ABOUT,(STRPTR)MSG_MEN_ABOUT_STR},
    {MSG_MEN_ABOUT_SC,(STRPTR)MSG_MEN_ABOUT_SC_STR},
    {MSG_MEN_QUIT,(STRPTR)MSG_MEN_QUIT_STR},
    {MSG_MEN_QUIT_SC,(STRPTR)MSG_MEN_QUIT_SC_STR},
    {MSG_FRAME_CLIPBOARD,(STRPTR)MSG_FRAME_CLIPBOARD_STR},
    {MSG_IMAGE_CLIPBOARD,(STRPTR)MSG_IMAGE_CLIPBOARD_STR},
    {MSG_GAD_TEST,(STRPTR)MSG_GAD_TEST_STR},
    {MSG_GAD_SAVE,(STRPTR)MSG_GAD_SAVE_STR},
    {MSG_GAD_USE,(STRPTR)MSG_GAD_USE_STR},
    {MSG_GAD_CANCEL,(STRPTR)MSG_GAD_CANCEL_STR},
    {MSG_DSC_SYSTEM,(STRPTR)MSG_DSC_SYSTEM_STR},
    {MSG_DSC_WINDOWS,(STRPTR)MSG_DSC_WINDOWS_STR},
    {MSG_DSC_GROUPS,(STRPTR)MSG_DSC_GROUPS_STR},
    {MSG_DSC_BUTTONS,(STRPTR)MSG_DSC_BUTTONS_STR},
    {MSG_DSC_CYCLES,(STRPTR)MSG_DSC_CYCLES_STR},
    {MSG_DSC_SLIDERS,(STRPTR)MSG_DSC_SLIDERS_STR},
    {MSG_DSC_SCROLLBARS,(STRPTR)MSG_DSC_SCROLLBARS_STR},
    {MSG_DSC_LISTVIEWS,(STRPTR)MSG_DSC_LISTVIEWS_STR},
    {MSG_DSC_STRINGS,(STRPTR)MSG_DSC_STRINGS_STR},
    {MSG_DSC_NAVIGATION,(STRPTR)MSG_DSC_NAVIGATION_STR},
    {MSG_DSC_SPECIAL,(STRPTR)MSG_DSC_SPECIAL_STR},
    {MSG_DSC_FRAMES,(STRPTR)MSG_DSC_FRAMES_STR},
    {MSG_ADJUST_PEN,(STRPTR)MSG_ADJUST_PEN_STR},
    {MSG_CUSTOMFRAMES,(STRPTR)MSG_CUSTOMFRAMES_STR},
    {MSG_PUBLIC_SCREEN,(STRPTR)MSG_PUBLIC_SCREEN_STR},
    {MSG_NAME,(STRPTR)MSG_NAME_STR},
    {MSG_CALL_INSPECTOR,(STRPTR)MSG_CALL_INSPECTOR_STR},
    {MSG_POP_TO_FRONT,(STRPTR)MSG_POP_TO_FRONT_STR},
    {MSG_ICONIFICATION,(STRPTR)MSG_ICONIFICATION_STR},
    {MSG_HOTKEY,(STRPTR)MSG_HOTKEY_STR},
    {MSG_SHOW,(STRPTR)MSG_SHOW_STR},
    {MSG_ICON,(STRPTR)MSG_ICON_STR},
    {MSG_MENU,(STRPTR)MSG_MENU_STR},
    {MSG_ON_STARTUP,(STRPTR)MSG_ON_STARTUP_STR},
    {MSG_INTERFACES,(STRPTR)MSG_INTERFACES_STR},
    {MSG_AREXX,(STRPTR)MSG_AREXX_STR},
    {MSG_BUBBLE_HELP,(STRPTR)MSG_BUBBLE_HELP_STR},
    {MSG_FIRST_BUBBLE,(STRPTR)MSG_FIRST_BUBBLE_STR},
    {MSG_NEXT_BUBBLE,(STRPTR)MSG_NEXT_BUBBLE_STR},
};

#endif /* CATCOMP_ARRAY */


/****************************************************************************/


#ifdef CATCOMP_BLOCK

static const char CatCompBlock[] =
{
    "\x00\x00\x00\x00\x00\x08"
    MSG_GENERAL_STR "\x00"
    "\x00\x00\x00\x01\x00\x0C"
    MSG_BACKGROUND_COLON_STR "\x00"
    "\x00\x00\x00\x02\x00\x1E"
    MSG_BACKGROUND_PRESSED_STR "\x00\x00"
    "\x00\x00\x00\x03\x00\x0E"
    MSG_TEXT_BUTTONS_STR "\x00\x00"
    "\x00\x00\x00\x04\x00\x08"
    MSG_FRAME_COLON_STR "\x00\x00"
    "\x00\x00\x00\x05\x00\x06"
    MSG_FONT_STR "\x00"
    "\x00\x00\x00\x06\x00\x0E"
    MSG_IMAGE_BUTTONS_STR "\x00"
    "\x00\x00\x00\x07\x00\x0E"
    MSG_ADJUST_FRAME_STR "\x00\x00"
    "\x00\x00\x00\x08\x00\x0C"
    MSG_CHECKMARKS_STR "\x00\x00"
    "\x00\x00\x00\x09\x00\x06"
    MSG_LOOK_COLON_STR "\x00"
    "\x00\x00\x00\x0A\x00\x0A"
    MSG_CHECKMARK_STR "\x00"
    "\x00\x00\x00\x0B\x00\x0E"
    MSG_RADIO_BUTTONS_STR "\x00"
    "\x00\x00\x00\x0C\x00\x0C"
    MSG_RADIOBUTTON_STR "\x00"
    "\x00\x00\x00\x0D\x00\x06"
    MSG_LOOK_STR "\x00\x00"
    "\x00\x00\x00\x0E\x00\x02"
    MSG_H_STR "\x00"
    "\x00\x00\x00\x0F\x00\x02"
    MSG_V_STR "\x00"
    "\x00\x00\x00\x10\x00\x08"
    MSG_SPACING_STR "\x00"
    "\x00\x00\x00\x11\x00\x06"
    MSG_BELOW_STR "\x00"
    "\x00\x00\x00\x12\x00\x0A"
    MSG_ON_ACTIVE_STR "\x00"
    "\x00\x00\x00\x13\x00\x14"
    MSG_CYCLE_GADGET_DESIGN_STR "\x00"
    "\x00\x00\x00\x14\x00\x06"
    MSG_CYCLE_STR "\x00"
    "\x00\x00\x00\x15\x00\x14"
    MSG_POPUP_MENU_CONTROL_STR "\x00\x00"
    "\x00\x00\x00\x16\x00\x0A"
    MSG_POSITION_STR "\x00"
    "\x00\x00\x00\x17\x00\x08"
    MSG_LEVEL_STR "\x00\x00"
    "\x00\x00\x00\x18\x00\x08"
    MSG_SPEED_STR "\x00\x00"
    "\x00\x00\x00\x19\x00\x12"
    MSG_POPUP_MENU_DESIGN_STR "\x00"
    "\x00\x00\x00\x1A\x00\x06"
    MSG_FRAME_STR "\x00"
    "\x00\x00\x00\x1B\x00\x12"
    MSG_ADJUST_BACKGROUND_STR "\x00"
    "\x00\x00\x00\x1C\x00\x0C"
    MSG_BACKGROUND_STR "\x00\x00"
    "\x00\x00\x00\x1D\x00\x12"
    MSG_RECESSED_ENTRIES_STR "\x00"
    "\x00\x00\x00\x1E\x00\x06"
    MSG_ABOVE_STR "\x00"
    "\x00\x00\x00\x1F\x00\x0A"
    MSG_CENTERED_STR "\x00\x00"
    "\x00\x00\x00\x20\x00\x0A"
    MSG_STANDARD_STR "\x00\x00"
    "\x00\x00\x00\x21\x00\x08"
    MSG_HILITE_STR "\x00\x00"
    "\x00\x00\x00\x22\x00\x04"
    MSG_3D_STR "\x00\x00"
    "\x00\x00\x00\x23\x00\x08"
    MSG_OUTLINE_STR "\x00"
    "\x00\x00\x00\x24\x00\x06"
    MSG_TITLE_STR "\x00"
    "\x00\x00\x00\x25\x00\x08"
    MSG_COLOR_STR "\x00\x00"
    "\x00\x00\x00\x26\x00\x0C"
    MSG_HORIZONTAL_STR "\x00"
    "\x00\x00\x00\x27\x00\x0A"
    MSG_VERTICAL_STR "\x00"
    "\x00\x00\x00\x28\x00\x0A"
    MSG_REGISTER_STR "\x00\x00"
    "\x00\x00\x00\x29\x00\x1E"
    MSG_DEFAULT_SIZE_TRUNCATE_TITLES_STR "\x00"
    "\x00\x00\x00\x2A\x00\x08"
    MSG_NORMAL_STR "\x00\x00"
    "\x00\x00\x00\x2B\x00\x08"
    MSG_VIRTUAL_STR "\x00"
    "\x00\x00\x00\x2C\x00\x08"
    MSG_FRAMED_STR "\x00\x00"
    "\x00\x00\x00\x2D\x00\x06"
    MSG_PAGE_STR "\x00\x00"
    "\x00\x00\x00\x2E\x00\x08"
    MSG_SHIFTED_STR "\x00"
    "\x00\x00\x00\x2F\x00\x08"
    MSG_ALWAYS_STR "\x00\x00"
    "\x00\x00\x00\x30\x00\x08"
    MSG_LINEAR_STR "\x00\x00"
    "\x00\x00\x00\x31\x00\x06"
    MSG_MIXED_STR "\x00"
    "\x00\x00\x00\x32\x00\x08"
    MSG_CONTROL_STR "\x00"
    "\x00\x00\x00\x33\x00\x08"
    MSG_MULTI_STR "\x00\x00"
    "\x00\x00\x00\x34\x00\x0A"
    MSG_REFRESH_STR "\x00\x00"
    "\x00\x00\x00\x35\x00\x08"
    MSG_SMOOTH_STR "\x00"
    "\x00\x00\x00\x36\x00\x06"
    MSG_FONTS_STR "\x00"
    "\x00\x00\x00\x37\x00\x08"
    MSG_NORMAL_COLON_STR "\x00"
    "\x00\x00\x00\x38\x00\x08"
    MSG_FIXED_STR "\x00\x00"
    "\x00\x00\x00\x39\x00\x08"
    MSG_LEADING_STR "\x00"
    "\x00\x00\x00\x3A\x00\x08"
    MSG_DESIGN_STR "\x00\x00"
    "\x00\x00\x00\x3B\x00\x0E"
    MSG_INPUT_LISTS_STR "\x00"
    "\x00\x00\x00\x3C\x00\x12"
    MSG_READONLY_LISTS_STR "\x00\x00"
    "\x00\x00\x00\x3D\x00\x08"
    MSG_CURSOR_STR "\x00\x00"
    "\x00\x00\x00\x3E\x00\x08"
    MSG_ACTIVE_STR "\x00"
    "\x00\x00\x00\x3F\x00\x14"
    MSG_ACTIVE_SELECTED_STR "\x00\x00"
    "\x00\x00\x00\x40\x00\x0A"
    MSG_SELECTED_STR "\x00"
    "\x00\x00\x00\x41\x00\x0E"
    MSG_ALWAYS_SOLID_STR "\x00\x00"
    "\x00\x00\x00\x42\x00\x10"
    MSG_GHOSTED_ON_BOX_STR "\x00\x00"
    "\x00\x00\x00\x43\x00\x14"
    MSG_GHOSTED_OUTSIDE_BOX_STR "\x00"
    "\x00\x00\x00\x44\x00\x10"
    MSG_ALWAYS_GHOSTED_STR "\x00\x00"
    "\x00\x00\x00\x45\x00\x0C"
    MSG_SHOW_FRAMES_STR "\x00"
    "\x00\x00\x00\x46\x00\x0E"
    MSG_SHOW_OBJECTS_STR "\x00\x00"
    "\x00\x00\x00\x47\x00\x08"
    MSG_KL_PRESS_STR "\x00\x00"
    "\x00\x00\x00\x48\x00\x08"
    MSG_KL_TOGGLE_STR "\x00"
    "\x00\x00\x00\x49\x00\x04"
    MSG_KL_UP_STR "\x00"
    "\x00\x00\x00\x4A\x00\x06"
    MSG_KL_DOWN_STR "\x00"
    "\x00\x00\x00\x4B\x00\x0A"
    MSG_KL_PAGE_UP_STR "\x00\x00"
    "\x00\x00\x00\x4C\x00\x0C"
    MSG_KL_PAGE_DOWN_STR "\x00\x00"
    "\x00\x00\x00\x4D\x00\x06"
    MSG_KL_TOP_STR "\x00\x00"
    "\x00\x00\x00\x4E\x00\x08"
    MSG_KL_BOTTOM_STR "\x00"
    "\x00\x00\x00\x4F\x00\x06"
    MSG_KL_LEFT_STR "\x00"
    "\x00\x00\x00\x50\x00\x08"
    MSG_KL_RIGHT_STR "\x00\x00"
    "\x00\x00\x00\x51\x00\x0C"
    MSG_KL_WORD_LEFT_STR "\x00\x00"
    "\x00\x00\x00\x52\x00\x0C"
    MSG_KL_WORD_RIGHT_STR "\x00"
    "\x00\x00\x00\x53\x00\x0C"
    MSG_KL_LINE_START_STR "\x00"
    "\x00\x00\x00\x54\x00\x0A"
    MSG_KL_LINE_END_STR "\x00"
    "\x00\x00\x00\x55\x00\x0E"
    MSG_KL_NEXT_GADGET_STR "\x00\x00"
    "\x00\x00\x00\x56\x00\x0E"
    MSG_KL_PREV_GADGET_STR "\x00"
    "\x00\x00\x00\x57\x00\x0C"
    MSG_KL_GADGET_OFF_STR "\x00"
    "\x00\x00\x00\x58\x00\x0E"
    MSG_KL_CLOSE_WINDOW_STR "\x00"
    "\x00\x00\x00\x59\x00\x0E"
    MSG_KL_NEXT_WINDOW_STR "\x00\x00"
    "\x00\x00\x00\x5A\x00\x0E"
    MSG_KL_PREV_WINDOW_STR "\x00"
    "\x00\x00\x00\x5B\x00\x06"
    MSG_KL_HELP_STR "\x00"
    "\x00\x00\x00\x5C\x00\x08"
    MSG_KL_POPUP_STR "\x00\x00"
    "\x00\x00\x00\x5D\x00\x0C"
    MSG_DRAG_DROP_STR "\x00"
    "\x00\x00\x00\x5E\x00\x0E"
    MSG_LEFT_BUTTON_STR "\x00\x00"
    "\x00\x00\x00\x5F\x00\x10"
    MSG_MIDDLE_BUTTON_STR "\x00\x00"
    "\x00\x00\x00\x60\x00\x0C"
    MSG_AUTOSTART_STR "\x00\x00"
    "\x00\x00\x00\x61\x00\x0A"
    MSG_PIXEL_STR "\x00"
    "\x00\x00\x00\x62\x00\x12"
    MSG_BALANCING_GROUPS_STR "\x00\x00"
    "\x00\x00\x00\x63\x00\x0A"
    MSG_EXAMPLE_STR "\x00\x00"
    "\x00\x00\x00\x64\x00\x0A"
    MSG_TRY_WITH_STR "\x00\x00"
    "\x00\x00\x00\x65\x00\x06"
    MSG_SHIFT_STR "\x00"
    "\x00\x00\x00\x66\x00\x06"
    MSG_TOO_STR "\x00\x00"
    "\x00\x00\x00\x67\x00\x12"
    MSG_KEYBOARD_CONTROL_STR "\x00\x00"
    "\x00\x00\x00\x68\x00\x18"
    MSG_COLOR_ACTIVE_OBJ_STR "\x00"
    "\x00\x00\x00\x69\x00\x08"
    MSG_NEWLOOK_STR "\x00"
    "\x00\x00\x00\x6A\x00\x08"
    MSG_CUSTOM_STR "\x00\x00"
    "\x00\x00\x00\x6B\x00\x08"
    MSG_ARROWS_STR "\x00\x00"
    "\x00\x00\x00\x6C\x00\x04"
    MSG_UP_STR "\x00\x00"
    "\x00\x00\x00\x6D\x00\x0A"
    MSG_ARROW_UP_STR "\x00\x00"
    "\x00\x00\x00\x6E\x00\x0C"
    MSG_ARROW_DOWN_STR "\x00\x00"
    "\x00\x00\x00\x6F\x00\x06"
    MSG_DOWN_STR "\x00\x00"
    "\x00\x00\x00\x70\x00\x06"
    MSG_LEFT_STR "\x00\x00"
    "\x00\x00\x00\x71\x00\x0C"
    MSG_ARROW_LEFT_STR "\x00\x00"
    "\x00\x00\x00\x72\x00\x0C"
    MSG_ARROW_RIGHT_STR "\x00"
    "\x00\x00\x00\x73\x00\x06"
    MSG_RIGHT_STR "\x00"
    "\x00\x00\x00\x74\x00\x04"
    MSG_BAR_STR "\x00"
    "\x00\x00\x00\x75\x00\x0E"
    MSG_GADGET_TYPE_STR "\x00\x00"
    "\x00\x00\x00\x76\x00\x0A"
    MSG_SCROLLER_STR "\x00\x00"
    "\x00\x00\x00\x77\x00\x06"
    MSG_KNOB_STR "\x00\x00"
    "\x00\x00\x00\x78\x00\x0C"
    MSG_ARRANGEMENT_STR "\x00"
    "\x00\x00\x00\x79\x00\x12"
    MSG_CONTAINER_DESIGN_STR "\x00\x00"
    "\x00\x00\x00\x7A\x00\x0C"
    MSG_KNOB_DESIGN_STR "\x00"
    "\x00\x00\x00\x7B\x00\x10"
    MSG_EXAMPLE_SLIDERS_STR "\x00"
    "\x00\x00\x00\x7C\x00\x0C"
    MSG_TEXT_FIELDS_STR "\x00"
    "\x00\x00\x00\x7D\x00\x12"
    MSG_EXAMPLE_TEXTFIELD_STR "\x00"
    "\x00\x00\x00\x7E\x00\x14"
    MSG_PROGRESS_INDICATOR_STR "\x00\x00"
    "\x00\x00\x00\x7F\x00\x0E"
    MSG_DEVICE_IMAGES_STR "\x00"
    "\x00\x00\x00\x80\x00\x08"
    MSG_DRAWER_STR "\x00\x00"
    "\x00\x00\x00\x81\x00\x0A"
    MSG_HARDDISK_STR "\x00\x00"
    "\x00\x00\x00\x82\x00\x06"
    MSG_DISK_STR "\x00\x00"
    "\x00\x00\x00\x83\x00\x04"
    MSG_RAM_STR "\x00"
    "\x00\x00\x00\x84\x00\x08"
    MSG_VOLUME_STR "\x00\x00"
    "\x00\x00\x00\x85\x00\x08"
    MSG_NETWORK_STR "\x00"
    "\x00\x00\x00\x86\x00\x08"
    MSG_ASSIGN_STR "\x00\x00"
    "\x00\x00\x00\x87\x00\x0C"
    MSG_TAPE_IMAGES_STR "\x00"
    "\x00\x00\x00\x88\x00\x0A"
    MSG_TAPE_PLAY_STR "\x00"
    "\x00\x00\x00\x89\x00\x0E"
    MSG_TAPE_PLAYBACK_STR "\x00"
    "\x00\x00\x00\x8A\x00\x0C"
    MSG_TAPE_PAUSE_STR "\x00\x00"
    "\x00\x00\x00\x8B\x00\x0A"
    MSG_TAPE_STOP_STR "\x00"
    "\x00\x00\x00\x8C\x00\x0C"
    MSG_TAPE_RECORD_STR "\x00"
    "\x00\x00\x00\x8D\x00\x08"
    MSG_TAPE_UP_STR "\x00"
    "\x00\x00\x00\x8E\x00\x0A"
    MSG_TAPE_DOWN_STR "\x00"
    "\x00\x00\x00\x8F\x00\x0E"
    MSG_STRING_FRAME_STR "\x00\x00"
    "\x00\x00\x00\x90\x00\x16"
    MSG_SPECIAL_POPUP_BUTTONS_STR "\x00"
    "\x00\x00\x00\x91\x00\x06"
    MSG_POPUP_STR "\x00"
    "\x00\x00\x00\x92\x00\x08"
    MSG_DEFAULT_STR "\x00"
    "\x00\x00\x00\x93\x00\x06"
    MSG_FILE_STR "\x00\x00"
    "\x00\x00\x00\x94\x00\x0C"
    MSG_POPUP_FILE_STR "\x00\x00"
    "\x00\x00\x00\x95\x00\x0E"
    MSG_POPUP_DRAWER_STR "\x00\x00"
    "\x00\x00\x00\x96\x00\x18"
    MSG_INACTIVE_STRING_COLORS_STR "\x00\x00"
    "\x00\x00\x00\x97\x00\x06"
    MSG_TEXT_STR "\x00\x00"
    "\x00\x00\x00\x98\x00\x16"
    MSG_ACTIVE_STRING_COLORS_STR "\x00\x00"
    "\x00\x00\x00\x99\x00\x16"
    MSG_MARKED_STRING_COLORS_STR "\x00\x00"
    "\x00\x00\x00\x9A\x00\x16"
    MSG_EXAMPLE_STRING_GADGET_STR "\x00"
    "\x00\x00\x00\x9B\x00\x10"
    MSG_FORGET_ON_EXIT_STR "\x00\x00"
    "\x00\x00\x00\x9C\x00\x12"
    MSG_REMEMBER_ON_EXIT_STR "\x00\x00"
    "\x00\x00\x00\x9D\x00\x0E"
    MSG_SAVE_ON_EXIT_STR "\x00\x00"
    "\x00\x00\x00\x9E\x00\x06"
    MSG_SMART_STR "\x00"
    "\x00\x00\x00\x9F\x00\x08"
    MSG_SIMPLE_STR "\x00\x00"
    "\x00\x00\x00\xA0\x00\x0E"
    MSG_WITHOUT_CLEAR_STR "\x00"
    "\x00\x00\x00\xA1\x00\x0C"
    MSG_WITH_CLEAR_STR "\x00\x00"
    "\x00\x00\x00\xA2\x00\x0C"
    MSG_POSITIONS_STR "\x00\x00"
    "\x00\x00\x00\xA3\x00\x08"
    MSG_REDRAW_STR "\x00"
    "\x00\x00\x00\xA4\x00\x06"
    MSG_TINY_STR "\x00"
    "\x00\x00\x00\xA5\x00\x06"
    MSG_BIG_STR "\x00\x00"
    "\x00\x00\x00\xA6\x00\x08"
    MSG_WINDOW_STR "\x00\x00"
    "\x00\x00\x00\xA7\x00\x0A"
    MSG_REQUESTER_STR "\x00"
    "\x00\x00\x00\xA8\x00\x02"
    MSG_L_STR "\x00"
    "\x00\x00\x00\xA9\x00\x02"
    MSG_T_STR "\x00"
    "\x00\x00\x00\xAA\x00\x02"
    MSG_R_STR "\x00"
    "\x00\x00\x00\xAB\x00\x02"
    MSG_B_STR "\x00"
    "\x00\x00\x00\xAC\x00\x08"
    MSG_BUTTONS_STR "\x00"
    "\x00\x00\x00\xAD\x00\x16"
    MSG_WINTITLE1_STR "\x00"
    "\x00\x00\x00\xAE\x00\x18"
    MSG_WINTITLE2_STR "\x00"
    "\x00\x00\x00\xAF\x00\x08"
    MSG_MEN_PROJECT_STR "\x00"
    "\x00\x00\x00\xB0\x00\x0A"
    MSG_MEN_OPEN_STR "\x00\x00"
    "\x00\x00\x00\xB1\x00\x02"
    MSG_MEN_OPEN_SC_STR "\x00"
    "\x00\x00\x00\xB2\x00\x0C"
    MSG_MEN_APPEND_STR "\x00\x00"
    "\x00\x00\x00\xB3\x00\x0C"
    MSG_MEN_SAVEAS_STR "\x00"
    "\x00\x00\x00\xB4\x00\x02"
    MSG_MEN_SAVEAS_SC_STR "\x00"
    "\x00\x00\x00\xB5\x00\x12"
    MSG_MEN_ABOUT_STR "\x00\x00"
    "\x00\x00\x00\xB6\x00\x02"
    MSG_MEN_ABOUT_SC_STR "\x00"
    "\x00\x00\x00\xB7\x00\x06"
    MSG_MEN_QUIT_STR "\x00\x00"
    "\x00\x00\x00\xB8\x00\x02"
    MSG_MEN_QUIT_SC_STR "\x00"
    "\x00\x00\x00\xB9\x00\x10"
    MSG_FRAME_CLIPBOARD_STR "\x00"
    "\x00\x00\x00\xBA\x00\x10"
    MSG_IMAGE_CLIPBOARD_STR "\x00"
    "\x00\x00\x00\xBB\x00\x06"
    MSG_GAD_TEST_STR "\x00"
    "\x00\x00\x00\xBC\x00\x06"
    MSG_GAD_SAVE_STR "\x00"
    "\x00\x00\x00\xBD\x00\x06"
    MSG_GAD_USE_STR "\x00\x00"
    "\x00\x00\x00\xBE\x00\x08"
    MSG_GAD_CANCEL_STR "\x00"
    "\x00\x00\x00\xBF\x00\x08"
    MSG_DSC_SYSTEM_STR "\x00\x00"
    "\x00\x00\x00\xC0\x00\x08"
    MSG_DSC_WINDOWS_STR "\x00"
    "\x00\x00\x00\xC1\x00\x08"
    MSG_DSC_GROUPS_STR "\x00\x00"
    "\x00\x00\x00\xC2\x00\x08"
    MSG_DSC_BUTTONS_STR "\x00"
    "\x00\x00\x00\xC3\x00\x08"
    MSG_DSC_CYCLES_STR "\x00\x00"
    "\x00\x00\x00\xC4\x00\x08"
    MSG_DSC_SLIDERS_STR "\x00"
    "\x00\x00\x00\xC5\x00\x0C"
    MSG_DSC_SCROLLBARS_STR "\x00\x00"
    "\x00\x00\x00\xC6\x00\x0A"
    MSG_DSC_LISTVIEWS_STR "\x00"
    "\x00\x00\x00\xC7\x00\x08"
    MSG_DSC_STRINGS_STR "\x00"
    "\x00\x00\x00\xC8\x00\x0C"
    MSG_DSC_NAVIGATION_STR "\x00\x00"
    "\x00\x00\x00\xC9\x00\x08"
    MSG_DSC_SPECIAL_STR "\x00"
    "\x00\x00\x00\xCA\x00\x08"
    MSG_DSC_FRAMES_STR "\x00\x00"
    "\x00\x00\x00\xCB\x00\x0C"
    MSG_ADJUST_PEN_STR "\x00\x00"
    "\x00\x00\x00\xCC\x00\x0E"
    MSG_CUSTOMFRAMES_STR "\x00\x00"
    "\x00\x00\x00\xCD\x00\x0E"
    MSG_PUBLIC_SCREEN_STR "\x00"
    "\x00\x00\x00\xCE\x00\x06"
    MSG_NAME_STR "\x00"
    "\x00\x00\x00\xCF\x00\x0E"
    MSG_CALL_INSPECTOR_STR "\x00\x00"
    "\x00\x00\x00\xD0\x00\x0E"
    MSG_POP_TO_FRONT_STR "\x00\x00"
    "\x00\x00\x00\xD1\x00\x0E"
    MSG_ICONIFICATION_STR "\x00"
    "\x00\x00\x00\xD2\x00\x08"
    MSG_HOTKEY_STR "\x00"
    "\x00\x00\x00\xD3\x00\x06"
    MSG_SHOW_STR "\x00"
    "\x00\x00\x00\xD4\x00\x06"
    MSG_ICON_STR "\x00\x00"
    "\x00\x00\x00\xD5\x00\x06"
    MSG_MENU_STR "\x00\x00"
    "\x00\x00\x00\xD6\x00\x0C"
    MSG_ON_STARTUP_STR "\x00\x00"
    "\x00\x00\x00\xD7\x00\x0C"
    MSG_INTERFACES_STR "\x00\x00"
    "\x00\x00\x00\xD8\x00\x06"
    MSG_AREXX_STR "\x00"
    "\x00\x00\x00\xD9\x00\x0C"
    MSG_BUBBLE_HELP_STR "\x00"
    "\x00\x00\x00\xDA\x00\x0E"
    MSG_FIRST_BUBBLE_STR "\x00"
    "\x00\x00\x00\xDB\x00\x0E"
    MSG_NEXT_BUBBLE_STR "\x00\x00"
};

#endif /* CATCOMP_BLOCK */


/****************************************************************************/


struct LocaleInfo
{
    APTR li_LocaleBase;
    APTR li_Catalog;
};


#ifdef CATCOMP_CODE

STRPTR GetString(struct LocaleInfo *li, LONG stringNum)
{
LONG   *l;
UWORD  *w;
STRPTR  builtIn;

    l = (LONG *)CatCompBlock;

    while (*l != stringNum)
    {
        w = (UWORD *)((ULONG)l + 4);
        l = (LONG *)((ULONG)l + (ULONG)*w + 6);
    }
    builtIn = (STRPTR)((ULONG)l + 6);

#define XLocaleBase LocaleBase
#define LocaleBase li->li_LocaleBase
    
    if (LocaleBase)
        return(GetCatalogStr(li->li_Catalog,stringNum,builtIn));
#define LocaleBase XLocaleBase
#undef XLocaleBase

    return(builtIn);
}


#endif /* CATCOMP_CODE */


/****************************************************************************/


#endif /* STRINGS_H */
